### ISSUE TITLE
Uncapitalized class names violating java naming conventions

### ISSUE THREAD

**Issue by ryanMMM** [The-CSC207-Group/Project207#11]
**Describe the bug**
There are many Command classes in the controller that have lower case names

**To Reproduce**
N/A, the code works but this is a code formatting issue

**Expected behavior**
Classes must have capitalized names by java conventions.

**Screenshots**
<img width="508" alt="image" src="https://user-images.githubusercontent.com/55326695/182738862-dc503a51-7873-47d5-b3be-114f1202f10d.png">

**Additional context**
N/A

**Comment by ahmedkhalf** [comment]
Fixed in pull request #12
