### ISSUE TITLE
Abstract admin user management into a seperate controller

### ISSUE THREAD

**Issue by ryanMMM** [The-CSC207-Group/Project207#5]
**Is your feature request related to a problem? Please describe.**
The admin help menu is bloated with too many commands and would get even bigger if we were to add new user types.

**Describe the solution you'd like**
To make the program more extensible, and the admin help menu cleaner, I would like to create a user management controller that handles the creation and deletions of users by the admin. This would abstract some of the already existing admin commands into a seperate controller.

**Describe alternatives you've considered**
I have considered storing all the admin commands in the same class, but i find that this makes the help menu of the admin too big.

**Additional context**
N/A

**Comment by ahmedkhalf** [comment]
That sounds like a great idea, you may go ahead and create a pr for it.

**Comment by ahmedkhalf** [comment]
Fixed in pull request #9
